apiVersion: 1

datasources:
  - uid: crypto-pg
    name: CryptoDB
    type: postgres
    url: postgres-crypto:5432
    database: crypto_db
    user: crypto
    secureJsonData:
      password: crypto123
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    editable: false
